apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-desk-data
  namespace: atlas-desk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
