apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-minipay-gateway
  namespace: atlas-desk
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: minipay
  to:
    - group: ""
      kind: Service
      name: atlas-desk
